#!/bin/sh

#ffmpeg -ss {start time(seconds)} -t {seconds to record for} -i {inputFile} {outputFile}
if [ $# -ne 3 ]; then
  echo '\n\033[1m\033[31mInvalid usage. Correct usage:\033[0m \n'
  echo './trim <file-to-trim> <start-time> <duration> \n'
  exit
fi

ffmpeg -ss $2 -t $3 -i audioFiles/$1.flac audioFiles/$1_trimmed.flac